# Copyright 2022 Nho Luong DevOps.
# SPDX-License-Identifier: Apache-2.0

include ../../Makefile-modules.mk

lint:
	echo "Skipping lint for broken module depprobcheck"

test:
	echo "Skipping test for broken module depprobcheck"

build:
	echo "Skipping build for broken module depprobcheck"
